locations:
  - UTC
  - America/Los_Angeles
  - Europe/London
  - Europe/Berlin
  - Asia/Tokyo
  - Australia/Sydney
input_formats:
  - "%Y-%m-%d %H:%M %Z"
  - "%Y-%m-%d %H:%M:%S %Z"
  - "%Y/%m/%d %H:%M %Z"
  - "%Y/%m/%d %H:%M:%S %Z"
output_format: "%Y-%m-%d %H:%M:%S %z"
